
services:
  leetcode_api:
    build:
      context: ./leetcode-api
      dockerfile: Dockerfile
    container_name: leetcode-api
    ports:
      - "3000:3000"
    restart: always
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REDIS_HOST=redis  # Added for Redis connection
      - REDIS_PORT=6379  # Added for Redis connection
    volumes:
      - ./leetcode-api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis  # Ensure Redis starts before the backend

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - leetcode_api

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"  # Optional, for external access